In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\win-11\appdata\local\programs\python\python312\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\win-11\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\win-11\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\win-11\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\win-11\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\win-11\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.1
[notice] To update, run: C:\Users\WIN-11\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
s=pd.Series([1,2,3])
print(s)

0    1
1    2
2    3
dtype: int64

In [4]:
data={"Name":["Ann","Anu"],"Age":[10,12]}
df=pd.DataFrame(data)
print(df)

  Name  Age
0  Ann   10
1  Anu   12

In [19]:
df=pd.read_csv("global_placement.csv")
display(df)
df.to_csv("output.csv",index=False)
display(df.head())
display(df.tail())
display(df.info())
display(df.describe())
display(df["cgpa"],df["college_tier"])
print(df.loc[0])
print(df.iloc[0])

,cgpa,backlogs,college_tier,country,university_ranking_band,internship_count,aptitude_score,communication_score,specialization,industry,internship_quality_score,placement_status,salary
0,7.397371,1,Tier 2,Canada,100-300,2,53.574150,64.177062,Data Science,Consulting,5.481450,Placed,104124.36780
1,6.889389,0,Tier 3,UK,300+,1,60.687750,88.346052,Data Science,Consulting,4.625099,Placed,80586.83831
2,7.518151,0,Tier 1,UK,100-300,2,64.568750,69.493171,Cybersecurity,Healthcare,5.227939,Placed,114444.31810
3,8.218424,0,Tier 2,UK,100-300,3,73.461500,78.204854,AI/ML,Tech,5.150674,Placed,120000.00000
4,6.812677,1,Tier 2,USA,100-300,4,86.518121,44.680881,Data Science,Consulting,3.888824,Placed,120000.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,8.040882,0,Tier 3,USA,100-300,2,98.120449,80.866213,Data Science,Manufacturing,6.298524,Placed,109831.58430
9996,5.401324,3,Tier 1,UK,100-300,1,68.622854,83.458035,Data Science,Consulting,7.352717,Not Placed,0.00000
9997,6.435747,0,Tier 3,UK,300+,2,69.067773,50.992745,Core CS,Other,3.871205,Placed,69818.81935
9998,7.396612,1,Tier 3,Germany,100-300,3,45.050463,86.807882,Cloud,Finance,3.687731,Placed,82797.57742
9999,7.515511,3,Tier 2,UK,300+,4,66.947232,46.385843,AI/ML,Manufacturing,4.181389,Placed,105387.85910

,cgpa,backlogs,college_tier,country,university_ranking_band,internship_count,aptitude_score,communication_score,specialization,industry,internship_quality_score,placement_status,salary
0,7.397371,1,Tier 2,Canada,100-300,2,53.574150,64.177062,Data Science,Consulting,5.481450,Placed,104124.36780
1,6.889389,0,Tier 3,UK,300+,1,60.687750,88.346052,Data Science,Consulting,4.625099,Placed,80586.83831
2,7.518151,0,Tier 1,UK,100-300,2,64.568750,69.493171,Cybersecurity,Healthcare,5.227939,Placed,114444.31810
3,8.218424,0,Tier 2,UK,100-300,3,73.461500,78.204854,AI/ML,Tech,5.150674,Placed,120000.00000
4,6.812677,1,Tier 2,USA,100-300,4,86.518121,44.680881,Data Science,Consulting,3.888824,Placed,120000.00000

,cgpa,backlogs,college_tier,country,university_ranking_band,internship_count,aptitude_score,communication_score,specialization,industry,internship_quality_score,placement_status,salary
9995,8.040882,0,Tier 3,USA,100-300,2,98.120449,80.866213,Data Science,Manufacturing,6.298524,Placed,109831.58430
9996,5.401324,3,Tier 1,UK,100-300,1,68.622854,83.458035,Data Science,Consulting,7.352717,Not Placed,0.00000
9997,6.435747,0,Tier 3,UK,300+,2,69.067773,50.992745,Core CS,Other,3.871205,Placed,69818.81935
9998,7.396612,1,Tier 3,Germany,100-300,3,45.050463,86.807882,Cloud,Finance,3.687731,Placed,82797.57742
9999,7.515511,3,Tier 2,UK,300+,4,66.947232,46.385843,AI/ML,Manufacturing,4.181389,Placed,105387.85910

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   cgpa                      10000 non-null  float64
 1   backlogs                  10000 non-null  int64
 2   college_tier              10000 non-null  object
 3   country                   10000 non-null  object
 4   university_ranking_band   10000 non-null  object
 5   internship_count          10000 non-null  int64
 6   aptitude_score            10000 non-null  float64
 7   communication_score       10000 non-null  float64
 8   specialization            10000 non-null  object
 9   industry                  10000 non-null  object
 10  internship_quality_score  10000 non-null  float64
 11  placement_status          10000 non-null  object
 12  salary                    10000 non-null  float64
dtypes: float64(5), int64(2), object(6)
memory usage: 1015.8+ KB

None

,cgpa,backlogs,internship_count,aptitude_score,communication_score,internship_quality_score,salary
count,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000
mean,6.998290,1.248100,1.49930,69.877531,65.158600,5.021436,55442.146458
std,0.802606,1.149904,1.20289,14.700532,14.740446,1.505975,47995.029325
min,4.000000,0.000000,0.00000,30.000000,30.000000,1.000000,0.000000
25%,6.461928,0.000000,1.00000,59.880399,55.112244,4.012656,0.000000
50%,6.997924,1.000000,1.00000,70.097368,65.006484,5.017335,63431.317260
75%,7.536865,2.000000,2.00000,80.213934,75.277248,6.031400,100600.617450
max,10.000000,6.000000,5.00000,100.000000,100.000000,10.000000,120000.000000

0       7.397371
1       6.889389
2       7.518151
3       8.218424
4       6.812677
          ...
9995    8.040882
9996    5.401324
9997    6.435747
9998    7.396612
9999    7.515511
Name: cgpa, Length: 10000, dtype: float64

0       Tier 2
1       Tier 3
2       Tier 1
3       Tier 2
4       Tier 2
         ...
9995    Tier 3
9996    Tier 1
9997    Tier 3
9998    Tier 3
9999    Tier 2
Name: college_tier, Length: 10000, dtype: object

cgpa                            7.397371
backlogs                               1
college_tier                      Tier 2
country                           Canada
university_ranking_band          100-300
internship_count                       2
aptitude_score                  53.57415
communication_score            64.177062
specialization              Data Science
industry                      Consulting
internship_quality_score         5.48145
placement_status                  Placed
salary                       104124.3678
Name: 0, dtype: object
cgpa                            7.397371
backlogs                               1
college_tier                      Tier 2
country                           Canada
university_ranking_band          100-300
internship_count                       2
aptitude_score                  53.57415
communication_score            64.177062
specialization              Data Science
industry                      Consulting
internship_quality_score         5.48145
placement_status                  Placed
salary                       104124.3678
Name: 0, dtype: object